### ISSUE TITLE
Case sensitivity on generated setting

### ISSUE THREAD

**Issue by Kevmscotland** [ZaarourOmar/PowerPortalWebAPIHelper#1]
We've recently started utilising the Web API and your excellent tool.
Historically we've had some inconsistency in our naming conventions, so a schema name can be "prefix_name", or "prefix_Name" (for example).

The site settings created by the API Tool always seem to favour lower case and thus don't quite match the schema.
Its easy enough thing to track down and change manually but worth noting

**Comment by Kevmscotland** [comment]
Examples:

Field 1
![image](https://user-images.githubusercontent.com/10791668/109388665-623c1e00-7900-11eb-9edb-f1bfe640a12e.png)

Field 2
![image](https://user-images.githubusercontent.com/10791668/109388667-6e27e000-7900-11eb-99fd-02a26481ceee.png)

Site Setting
![image](https://user-images.githubusercontent.com/10791668/109388673-7aac3880-7900-11eb-851b-596e9db4810e.png)

**Comment by ZaarourOmar** [comment]
> Examples:
> 
> Field 1
> ![image](https://user-images.githubusercontent.com/10791668/109388665-623c1e00-7900-11eb-9edb-f1bfe640a12e.png)
> 
> Field 2
> ![image](https://user-images.githubusercontent.com/10791668/109388667-6e27e000-7900-11eb-99fd-02a26481ceee.png)
> 
> Site Setting
> ![image](https://user-images.githubusercontent.com/10791668/109388673-7aac3880-7900-11eb-851b-596e9db4810e.png)

@Kevmscotland  Thanks so much. That is a problem for sure. When I built this tool, I didn't have all the info I needed from the MSFT docs and that's why it is missing things. I will start improving it and will be fixing this issue hopefully soon. 
regards,
Omar

**Comment by ZaarourOmar** [comment]
Hi @Kevmscotland , I just released an upgrade that should take care of your issue. As more docs come in for this feature, I will update the tool further.

Thanks a lot for your comments here.

**Comment by Kevmscotland** [comment]
@ZaarourOmar That's fantastic. Thanks for your hard work 🥇
