### ISSUE TITLE
Duplicated Fields

### ISSUE THREAD

**Issue by alduzzen1985** [ZaarourOmar/PowerPortalWebAPIHelper#2]
Hi,

I've found a small bug. If you pick two times an entity, it loads two times the list of the attributes.

![image](https://user-images.githubusercontent.com/32884589/113272326-67abd000-92d3-11eb-88db-7302893cde7c.png)

Best regards,

Aldo

**Comment by ZaarourOmar** [comment]
Thanks so much, will be fixing this soon.
